language: java

jdk:
    - oraclejdk7

service:
    - mysql

before_install:
    - mysql -h localhost -u root < demo-struts2-web/src/test/resources/sql/USER.sql

install:
    - mvn install -Dmaven.test.skip=true
