CREATE DATABASE IF NOT EXISTS demos;
USE demos;
DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER` (
  `ID` int(11) NOT NULL,
  `USERNAME` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

INSERT INTO `USER` VALUES ('1', 'admin');
INSERT INTO `USER` VALUES ('2', 'gorden5566');
INSERT INTO `USER` VALUES ('3', 'test');
